# Generated by Django 5.0.6 on 2024-07-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
