# Generated by Django 5.0.6 on 2024-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0002_menu_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='PedCli',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
