# Generated by Django 5.0.6 on 2024-07-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0003_pedido_pedcli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='PedObs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
