# Generated by Django 5.0.6 on 2024-07-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0006_remove_pedidodetalle_pedobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='EstMesCod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurante_app.estadomesa'),
        ),
    ]
